name: NodeJS with Webpack

on:
  push:
    branches: [ main , feat/gautam/tests]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        # npx webpack
        npm test
        npm run build
      env:
        MYSQL_HOST: us-cdbr-east-04.cleardb.com
        MYSQL_USER: b01eb9170bdd13
        MYSQL_DATABASE: heroku_c2fca39d7a7384f
        MYSQL_PASSWORD: fd7ba9ac
