name: NodeJS with Webpack

on:
  push:
    branches: [ main , feat/gautam/tests]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm test
      env:
        MYSQL_HOST: us-cdbr-east-04.cleardb.com
        MYSQL_USER: b01eb9170bdd13
        MYSQL_DATABASE: heroku_c2fca39d7a7384f
        MYSQL_PASSWORD: fd7ba9ac
        REDIS_URL: redis://:p8a9a536e37e24dcb479b2badb88bf9dc7808ed53900c90a23d5f3d88519eb8f6@ec2-54-156-199-127.compute-1.amazonaws.com:32020
        SESSION_SECRET_KEY: team42-crm